# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='filter.proto',
  package='filter',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x66ilter.proto\x12\x06\x66ilter\"$\n\x0e\x43onnectRequest\x12\x12\n\nfilterPort\x18\x01 \x01(\x03\"\x11\n\x0f\x43onnectResponse\"\x1b\n\x0bTestMessage\x12\x0c\n\x04test\x18\x01 \x01(\t\"#\n\x13TestMessageResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x11\n\x0f\x44\x65\x63reaseRequest\"\x12\n\x10\x44\x65\x63reaseResponse\"\x11\n\x0fIncreaseRequest\"\x12\n\x10IncreaseResponse2\xad\x02\n\rFilterService\x12\x44\n\x0eGetTestMessage\x12\x13.filter.TestMessage\x1a\x1b.filter.TestMessageResponse\"\x00\x12<\n\x07\x43onnect\x12\x16.filter.ConnectRequest\x1a\x17.filter.ConnectResponse\"\x00\x12K\n\x14\x44\x65\x63reaseCountClients\x12\x17.filter.DecreaseRequest\x1a\x18.filter.DecreaseResponse\"\x00\x12K\n\x14IncreaseCountClients\x12\x17.filter.IncreaseRequest\x1a\x18.filter.IncreaseResponse\"\x00\x62\x06proto3'
)




_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='filter.ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filterPort', full_name='filter.ConnectRequest.filterPort', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=60,
)


_CONNECTRESPONSE = _descriptor.Descriptor(
  name='ConnectResponse',
  full_name='filter.ConnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=79,
)


_TESTMESSAGE = _descriptor.Descriptor(
  name='TestMessage',
  full_name='filter.TestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='test', full_name='filter.TestMessage.test', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=108,
)


_TESTMESSAGERESPONSE = _descriptor.Descriptor(
  name='TestMessageResponse',
  full_name='filter.TestMessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='filter.TestMessageResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=145,
)


_DECREASEREQUEST = _descriptor.Descriptor(
  name='DecreaseRequest',
  full_name='filter.DecreaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=164,
)


_DECREASERESPONSE = _descriptor.Descriptor(
  name='DecreaseResponse',
  full_name='filter.DecreaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=184,
)


_INCREASEREQUEST = _descriptor.Descriptor(
  name='IncreaseRequest',
  full_name='filter.IncreaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=203,
)


_INCREASERESPONSE = _descriptor.Descriptor(
  name='IncreaseResponse',
  full_name='filter.IncreaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=223,
)

DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['ConnectResponse'] = _CONNECTRESPONSE
DESCRIPTOR.message_types_by_name['TestMessage'] = _TESTMESSAGE
DESCRIPTOR.message_types_by_name['TestMessageResponse'] = _TESTMESSAGERESPONSE
DESCRIPTOR.message_types_by_name['DecreaseRequest'] = _DECREASEREQUEST
DESCRIPTOR.message_types_by_name['DecreaseResponse'] = _DECREASERESPONSE
DESCRIPTOR.message_types_by_name['IncreaseRequest'] = _INCREASEREQUEST
DESCRIPTOR.message_types_by_name['IncreaseResponse'] = _INCREASERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTREQUEST,
  '__module__' : 'filter_pb2'
  # @@protoc_insertion_point(class_scope:filter.ConnectRequest)
  })
_sym_db.RegisterMessage(ConnectRequest)

ConnectResponse = _reflection.GeneratedProtocolMessageType('ConnectResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTRESPONSE,
  '__module__' : 'filter_pb2'
  # @@protoc_insertion_point(class_scope:filter.ConnectResponse)
  })
_sym_db.RegisterMessage(ConnectResponse)

TestMessage = _reflection.GeneratedProtocolMessageType('TestMessage', (_message.Message,), {
  'DESCRIPTOR' : _TESTMESSAGE,
  '__module__' : 'filter_pb2'
  # @@protoc_insertion_point(class_scope:filter.TestMessage)
  })
_sym_db.RegisterMessage(TestMessage)

TestMessageResponse = _reflection.GeneratedProtocolMessageType('TestMessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTMESSAGERESPONSE,
  '__module__' : 'filter_pb2'
  # @@protoc_insertion_point(class_scope:filter.TestMessageResponse)
  })
_sym_db.RegisterMessage(TestMessageResponse)

DecreaseRequest = _reflection.GeneratedProtocolMessageType('DecreaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _DECREASEREQUEST,
  '__module__' : 'filter_pb2'
  # @@protoc_insertion_point(class_scope:filter.DecreaseRequest)
  })
_sym_db.RegisterMessage(DecreaseRequest)

DecreaseResponse = _reflection.GeneratedProtocolMessageType('DecreaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _DECREASERESPONSE,
  '__module__' : 'filter_pb2'
  # @@protoc_insertion_point(class_scope:filter.DecreaseResponse)
  })
_sym_db.RegisterMessage(DecreaseResponse)

IncreaseRequest = _reflection.GeneratedProtocolMessageType('IncreaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _INCREASEREQUEST,
  '__module__' : 'filter_pb2'
  # @@protoc_insertion_point(class_scope:filter.IncreaseRequest)
  })
_sym_db.RegisterMessage(IncreaseRequest)

IncreaseResponse = _reflection.GeneratedProtocolMessageType('IncreaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _INCREASERESPONSE,
  '__module__' : 'filter_pb2'
  # @@protoc_insertion_point(class_scope:filter.IncreaseResponse)
  })
_sym_db.RegisterMessage(IncreaseResponse)



_FILTERSERVICE = _descriptor.ServiceDescriptor(
  name='FilterService',
  full_name='filter.FilterService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=226,
  serialized_end=527,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTestMessage',
    full_name='filter.FilterService.GetTestMessage',
    index=0,
    containing_service=None,
    input_type=_TESTMESSAGE,
    output_type=_TESTMESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='filter.FilterService.Connect',
    index=1,
    containing_service=None,
    input_type=_CONNECTREQUEST,
    output_type=_CONNECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DecreaseCountClients',
    full_name='filter.FilterService.DecreaseCountClients',
    index=2,
    containing_service=None,
    input_type=_DECREASEREQUEST,
    output_type=_DECREASERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IncreaseCountClients',
    full_name='filter.FilterService.IncreaseCountClients',
    index=3,
    containing_service=None,
    input_type=_INCREASEREQUEST,
    output_type=_INCREASERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILTERSERVICE)

DESCRIPTOR.services_by_name['FilterService'] = _FILTERSERVICE

# @@protoc_insertion_point(module_scope)
